// <auto-generated />
using System;
using MMO_EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MMO_EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MMO_EFCore.Guild", b =>
                {
                    b.Property<int?>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GuildName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuildId");

                    b.ToTable("Guild");
                });

            modelBuilder.Entity("MMO_EFCore.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecoveredDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasDiscriminator<int>("Type").HasValue(0);
                });

            modelBuilder.Entity("MMO_EFCore.ItemDetail", b =>
                {
                    b.Property<int>("ItemDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemDetailId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MMO_EFCore.ItemReview", b =>
                {
                    b.Property<int>("ItemReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("ItemReviewId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemReview");
                });

            modelBuilder.Entity("MMO_EFCore.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GuildId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("PlayerId");

                    b.HasIndex("GuildId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("Index_Person_Name");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("MMO_EFCore.EventItem", b =>
                {
                    b.HasBaseType("MMO_EFCore.Item");

                    b.Property<DateTime>("DestroyDate")
                        .HasColumnType("datetime2");

                    b.ToTable("Item");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("MMO_EFCore.Item", b =>
                {
                    b.HasOne("MMO_EFCore.Player", "Creator")
                        .WithMany("CreatedItems")
                        .HasForeignKey("CreatorId");

                    b.HasOne("MMO_EFCore.Player", "Owner")
                        .WithOne("OwnedItem")
                        .HasForeignKey("MMO_EFCore.Item", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MMO_EFCore.ItemOption", "Option", b1 =>
                        {
                            b1.Property<int>("ItemId")
                                .HasColumnType("int");

                            b1.Property<int>("Dex")
                                .HasColumnType("int");

                            b1.Property<int>("HP")
                                .HasColumnType("int");

                            b1.Property<int>("Str")
                                .HasColumnType("int");

                            b1.HasKey("ItemId");

                            b1.ToTable("ItemOption");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });
                });

            modelBuilder.Entity("MMO_EFCore.ItemDetail", b =>
                {
                    b.HasOne("MMO_EFCore.Item", null)
                        .WithOne("Detail")
                        .HasForeignKey("MMO_EFCore.ItemDetail", "ItemDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MMO_EFCore.ItemReview", b =>
                {
                    b.HasOne("MMO_EFCore.Item", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("MMO_EFCore.Player", b =>
                {
                    b.HasOne("MMO_EFCore.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId");
                });
#pragma warning restore 612, 618
        }
    }
}
